# https://jupyterbook.org/customize/config.html

title: "Hongyuan's Portfolio"
author: Hongyuan

# https://jupyterbook.org/en/stable/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*
  - .venv/*

execute:
  execute_notebooks: "off"

html:
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false

sphinx:
  config:
    # https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets
    myst_heading_anchors: 4
    # https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
    plotly_include_js: "cdn"


    